spring:
  application:
    name: ASM2-PolyOE
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PolyOE;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail: # Cấu hình gửi Email (cho Gmail SMTP)
    host: smtp.gmail.com
    port: 587
    username: hieuvu0422@gmail.com
    password: mtoo mwzc jgqe dekk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml
server:
  port: 1212